version: "3.8"

services:
  web:
    build: .
    container_name: arcadia_web
    restart: always
    ports:
      - "8080:80"
    volumes:
    - ./front:/var/www/arcadia/front
    - ./lib:/var/www/arcadia/lib
    - ./templates:/var/www/arcadia/templates

    depends_on:
      - db
      - redis
    environment:
      - PHP_EXTENSION_REDIS=1
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - SERVERNAME=localhost
    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  db:
    image: mariadb:10.4
    container_name: arcadia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoo_arcadia
      MYSQL_USER: arcadia_user
      MYSQL_PASSWORD: arcadia_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: arcadia_redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: arcadia_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: arcadia_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
  sql_data:
